services:
  - type: web
    name: bist-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_bist.py"
    plan: starter
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Güvenlik için, değeri Render panelinden ekleyin
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: MIN_VOLUME_TRY
        value: "1000000"
      - key: MAX_SYMBOLS
        value: "100"
      - key: MIN_SIGNAL_SCORE
        value: "2.5"
      - key: CONCURRENCY
        value: "5"
      - key: SIGNAL_COOLDOWN_H
        value: "6"
      - key: MIN_PRICE
        value: "1.0"
      - key: SCAN_INTERVAL_SEC
        value: "900"
      - key: LOG_LEVEL
        value: "INFO"
