services:
  - type: web
    name: bist-scanner-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: COLLECTAPI_KEY
        sync: false
      - key: SCAN_MODE
        value: ALL
      - key: CUSTOM_TICKERS
        value: ""
      - key: CHECK_EVERY_MIN
        value: "15"
      - key: TIMEFRAMES
        value: "1d,4h,1h,15m"
      - key: MIN_PRICE
        value: "1.0"
      - key: MIN_VOLUME_TRY
        value: "1000000"
      - key: MIN_SIGNAL_SCORE
        value: "15.0"
      - key: LOG_LEVEL
        value: "INFO"
