services:
  - type: web
    name: bist-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 bot_bist.py"
    plan: starter
    healthCheckPath: /health
    envVars:
      # Ortam değişkenlerinizi Render paneline eklemelisiniz.
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: MIN_VOLUME_TRY
        value: "1000000"
      - key: MIN_SIGNAL_SCORE
        value: "2.5"
      - key: SCAN_INTERVAL_SEC
        value: "900"
      - key: CONCURRENCY
        value: "5"
      - key: TEST_MODE
        value: "false"
      - key: LOG_LEVEL
        value: "INFO"
      - key: SIGNAL_COOLDOWN_H
        value: "6"
      - key: MIN_PRICE
        value: "1.0"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "8080"
