services:
  - type: web
    name: rsi-bot-bist
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_bist.py
    plan: starter
    healthCheckPath: /health
    envVars:
      # Bot Configuration
      - key: TICKERS
        value: THYAO,SAHOL,ASTOR,AKBNK,SISE,BIMAS,EREGL,KCHOL
      - key: TIMEFRAMES
        value: 1h,4h,1d
      - key: CHECK_EVERY_MIN
        value: 15
      
      # RSI Parameters
      - key: RSI_LEN
        value: 22
      - key: RSI_EMA_LEN
        value: 66
      - key: PIVOT_PERIOD
        value: 10
      - key: ALERT_COOLDOWN_MIN
        value: 60
      
      # Enhanced Parameters
      - key: MIN_VOLUME_RATIO
        value: 1.5
      - key: MACD_FAST
        value: 12
      - key: MACD_SLOW
        value: 26
      - key: MACD_SIGNAL
        value: 9
      - key: BB_PERIOD
        value: 20
      - key: BB_MULT
        value: 2.0
      - key: CANDLE_FORM_THRESHOLD
        value: 0.7
      
      # Logging
      - key: LOG_LEVEL
        value: INFO
      
      # Secret variables (add these manually in Render dashboard)
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
