services:
  - type: worker
    name: cakmaustad-bot
    env: python
    buildCommand: |
      pip install --no-cache-dir tradingview_ta yfinance aiohttp python-dotenv pandas numpy pytz
    startCommand: python bot_bist.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: ${TELEGRAM_BOT_TOKEN}
      - key: TELEGRAM_CHAT_ID
        value: ${TELEGRAM_CHAT_ID}
      - key: SCAN_MODE
        value: ${SCAN_MODE}
      - key: CUSTOM_TICKERS
        value: ${CUSTOM_TICKERS}
      - key: CHECK_EVERY_MIN
        value: ${CHECK_EVERY_MIN}
      - key: TIMEFRAMES
        value: ${TIMEFRAMES}
      - key: MIN_PRICE
        value: ${MIN_PRICE}
      - key: MIN_VOLUME_TRY
        value: ${MIN_VOLUME_TRY}
      - key: MIN_SIGNAL_SCORE
        value: ${MIN_SIGNAL_SCORE}
      - key: LOG_LEVEL
        value: ${LOG_LEVEL}
      - key: CONCURRENT_REQUESTS
        value: ${CONCURRENT_REQUESTS}
